Dev Status (Git)
matryer/xbar-plugins pull request #1622
Opened 2021-05-15 21:14 UTC by khrome

This searches through a dir for any contained .git repos and displays them as a list, whether they are clean or not and allow you to click through. I use this to know, at a glance, what needs to be flushed when I'm in the midst of updating many modules (and potentially multiple contexts).

![menu](https://user-images.githubusercontent.com/494527/118378290-080e3900-b590-11eb-9af2-ca13c56a9a46.png)

2021-05-21 11:57 UTC, matryer requested changes
Nice. Just needs an image.

2021-05-21 11:57 UTC, matryer commented on Dev/Git/DevStatus.10m.sh
> +# <xbar.image></xbar.image>
Please provide the URL to an image for this plugin.

2021-05-21 11:57 UTC, matryer commented on Dev/Git/DevStatus.10m.sh
> +# <xbar.image></xbar.image>
p.s. you can use the one you posted in GitHub, they stick around.

2021-12-06 16:45 UTC, khrome commented
Is this dead/should I close it?

2021-12-06 17:09 UTC, merged