Initial add of the wol plugin
matryer/xbar-plugins pull request #1657
Opened 2021-07-09 19:15 UTC by The-Michael-R

I would like to contribute a small plugin that allows to monitor a specific server by ping a configurable IP address and on user-interaction wake the server.

Plugin:
![image](https://user-images.githubusercontent.com/21987859/125125512-fb264580-e0f9-11eb-83f4-80697c54e1ae.png)

Configuration:
![image](https://user-images.githubusercontent.com/21987859/125125753-59ebbf00-e0fa-11eb-81bb-77d04ed500a7.png)

2021-09-01 17:05 UTC, matryer requested changes
Nice job, please update the image. :)

2021-09-01 17:05 UTC, matryer commented on Tools/wol/wol-nas.10s.sh
> +#  <xbar.image>https://github.com/The-Michael-R/xbar-plugins/Tools/wol/wol_xbar.png</xbar.image>
This image is not found https://github.com/The-Michael-R/xbar-plugins/Tools/wol/wol_xbar.png

2021-09-01 17:19 UTC, The-Michael-R commented
Thanks. I hope that the updated link works now.

2021-09-01 17:22 UTC, matryer commented
@The-Michael-R I think it needs to be `https://github.com/The-Michael-R/xbar-plugins/blob/master/Tools/wol/wol_xbar.png?raw=true`?

2021-09-01 17:28 UTC, matryer commented
@The-Michael-R Great - except we don't want the image in the PR, just linked to in the `metadata` :) Sorry to be a pain.

2021-09-01 17:44 UTC, The-Michael-R commented
No problem. That's your repro and your rules. And that rule actually make sense.

Sorry for not be very experienced as that's my first PR to a _public_ repro.

2023-01-27 02:41 UTC, sprak3000 approved these changes

2023-01-27 02:41 UTC, merged