Add Pagerduty plugin
matryer/xbar-plugins pull request #1659
Opened 2021-07-10 07:20 UTC by seren

This plugin will display open Pagerduty incidents assigned to a user.

![Screen Shot 2021-07-10 at 12 19 11 AM](https://user-images.githubusercontent.com/512022/125155421-94625580-e114-11eb-9bcd-ddeb9811c81f.png)

2021-09-01 17:16 UTC, matryer requested changes
There are already some PagerDuty plugins, please ensure this doesn't duplicate behaviour.

2021-09-01 17:16 UTC, matryer commented on Dev/pagerduty.1m.sh
> +# <xbar.image>https://i.imgur.com/2p2nFg8.png</xbar.image>
Please use an image that shows the plugin when it's installed.

2021-09-11 00:42 UTC, seren commented
I don't think this duplicates behavior of the other three existing plugins, though `pagerDutyIncidents.30s.js` might be the closest. I'm unable to run any of them out of the box (fresh install of Mac OS 11.5.2) however:
- `pagerduty.30s.rb` fails to run due to missing ruby gem dependencies.
- `pagerDutyOnCall.30s.js` and `pagerDutyIncidents.30s.js` require node and a `.bitbarrc` config file, neither of which I have installed/created.

This version uses xbar variables and is a simple shell script, so it should work out of the box and be easy to configure via the xbar gui.

I've updated the image to show the plugin's menu.

2023-01-27 02:40 UTC, sprak3000 approved these changes

2023-01-27 02:40 UTC, merged