add zoom shortcuts plugin
matryer/xbar-plugins pull request #1766
Opened 2022-01-25 14:42 UTC by dievskiy

Simple plugin for quick access to zoom meetings. 

<img width="504" alt="zoom" src="https://user-images.githubusercontent.com/47274547/150997755-7a9f11ca-fce6-4cd2-a528-7cbdbf1595be.png">

2022-03-23 14:23 UTC, matryer requested changes

2022-03-23 14:23 UTC, matryer commented on Lifestyle/zoom_shortcuts.1d.sh
> +#  <xbar.desc>Plugin to open zoom meetings quickly</xbar.desc>
please add the image metadata

2023-01-27 02:46 UTC, sprak3000 commented
@dievskiy 

Could you run `chmod +x` on the file?

2023-01-27 14:27 UTC, sprak3000 approved these changes

2023-01-27 14:27 UTC, merged